# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=10)),
                ('kml', models.FileField(upload_to='kml_files')),
            ],
            options={
                'verbose_name': 'Ruta',
                'verbose_name_plural': 'Rustas',
            },
        ),
    ]
