# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-01 18:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backprocess', '0002_detalleruta_inforutausuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='RutaCoordendas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordenadas', models.CharField(max_length=50)),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backprocess.Ruta')),
            ],
        ),
    ]
