# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-01 18:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backprocess', '0003_rutacoordendas'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RutaCoordendas',
            new_name='RutaCoordenda',
        ),
    ]
