# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-01 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backprocess', '0004_auto_20170801_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rutacoordenda',
            name='coordenadas',
            field=models.CharField(max_length=150),
        ),
    ]
