# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-02 16:48
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backprocess', '0005_auto_20170801_2027'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalleruta',
            options={'verbose_name': 'Detalle ruta', 'verbose_name_plural': 'Detalle de rutas'},
        ),
        migrations.AlterModelOptions(
            name='inforutausuario',
            options={'verbose_name': 'Informaci\xf3n de usuario', 'verbose_name_plural': 'Informaci\xf3n de usuarios'},
        ),
        migrations.AlterModelOptions(
            name='ruta',
            options={'verbose_name': 'Ruta', 'verbose_name_plural': 'Rutas'},
        ),
        migrations.AlterField(
            model_name='rutacoordenda',
            name='coordenadas',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
    ]
