# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backprocess', '0006_auto_20170802_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='http_kml',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
