# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-08 20:11
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backprocess', '0007_ruta_http_kml'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodosRutas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nodo', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('ruta_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ruta_nodo_a', to='backprocess.Ruta')),
                ('ruta_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ruta_nodo_b', to='backprocess.Ruta')),
            ],
            options={
                'verbose_name': 'Nodo',
                'verbose_name_plural': 'Nodos',
            },
        ),
    ]
