# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-09 19:12
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backprocess', '0011_auto_20170809_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='puntos',
            field=django.contrib.gis.db.models.fields.LineStringField(null=True, srid=4326),
        ),
    ]
