# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-09 19:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backprocess', '0012_ruta_puntos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rutacoordenda',
            name='linea',
        ),
    ]
