# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 17:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backprocess', '0013_remove_rutacoordenda_linea'),
    ]

    operations = [
        migrations.CreateModel(
            name='Linea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Line',
                'verbose_name_plural': 'Lineas',
            },
        ),
        migrations.AddField(
            model_name='ruta',
            name='linea',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='backprocess.Linea'),
            preserve_default=False,
        ),
    ]
