# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 17:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backprocess', '0014_auto_20170906_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruta',
            name='linea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backprocess.Linea'),
        ),
    ]
